### ISSUE TITLE
The .msp.tsv have a wrong header

### ISSUE THREAD

**Issue by silvewheat** [AI-sandbox/SALAI-Net#1]
Hi,

The output file .msp.tsv should be the result of prediction for query samples. But it's header are reference samples. Thus the number of columns also doesn't matched.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/19344997/194898483-04b57cfc-650c-497a-b227-1c42f4f91689.png">

**Comment by benoriol** [comment]
Thanks for the comment, will review this and fix.

**Comment by benoriol** [comment]
As you suggested, it was taking the sample names from the refpanel. The bug has now been fixed. 
```
~/SALAI-Net/prediction_folder$ awk -F '\t' '{print NF}' predictions.msp.tsv | head
1276
1276
1276
1276
1276
1276
1276
```

Thank you for raising the issue and don't hesitate to open another one if something else comes up.

Thank you for your cooperation,

Benet
